workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "com.pphi.bhuapp"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS release .ipa
        script: |
          flutter build ipa --release --build-name=1.0.0 --build-number=1
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: Encrypted API Key → You can generate one in **App Store Connect**
